const Map<String, String> ar = {
  "UserName": "اسم المستخدم",
  "Login": "تسجيل الدخول",
  "Reset Password": "إعادة تعيين كلمة المرور",
  "OR": "أو",
  "incorrect email or password": "بريد أو كلمة مرورغير صحيحة",
  "Password": "كلمه المرور",
  "LOGIN": "الدخول",
  "SIGN UP": "التسجيل",
  "register": "تسجيل جديد",
  "Username": "اسم المستخدم",
  "Forgot your password?": "؟هل نسيت كلمة المرور",
  "Don't Have an Account? Sign up": "ليس لديك حساب؟ تسجيل حساب جديد",
  "REGISTER": "حساب جديد",
  "First Name": "الاسم الاول",
  "Tap back again to leave": "اضغط مرة اخرى للخروج",
  "Last Name": "الاسم الاخير",
  "Terms & Conditions": "الشروط و الاحكام",
  "Email": "البريد الالكتروني",
  "Agree to Terms": "موافق على الشروط",
  "Agree": "موافقة",
  "Mobile": "الهاتف",
  "Send": "ارسال",
  "Confirm Password": "تاكيد كلمة المرور",
  "you are sign in": "تم تسجيل الدخول",
  "Connection Failed Please Try Again Later": "فشل في الاتصال حاول مجددا",
  "UserName Is Already Exist": "اسم المستخدم موجود مسبقا",
  "Email Is Already Exist": "لبريد الالكتروني موجود مسبق",
  "Is Required": "مطلوب",
  "Should Be At Least 6 Characters": "يجب ان يكون علي الاقل 6 احرف",
  "Password and Confirm Password Doesn't Match":
  "كلمة المرور وتاكيد كلمة المرور ليسوا متشابهين",
  "Should Be At Least 4 Characters": "يجب ان يكون علي الاقل 4 احرف",
  "Invalid Email": "خطا في لبريد الالكتروني",
  "Next": "التالي",
  "Email Verified": "اكيد لبريد الالكتروني",
  "the code doesn't match check your code or change Email":
  "الكود لا يتطابق تاكد مجددا",
  "EMAIL VERIFICATION": "تاكيد لبريد الالكتروني",
  "verification code": "كود التحقق",
  "Verify": "تحقق",
  "Failed to load Countries": "خطا في تحميل الدول",
  "Failed to load Regions": "خطا في تحميل المنطقه",
  "Failed to load Cities": "خطا في تحميل المدن",
  "ADDRESS": "عنوان",
  "Select Country": "اختر الدولة",
  "Select City": "اختر المدينة",
  "Select Region": "اختر المنطقه",
  "Details": "تفاصيل",
  "Order No.:": "طلب رقم:",
  "Date: ": "التاريخ: ",
  "Status: ": "الحالة: ",
  "refused": "مرفوض",
  "Sell": "بيع",
  "accepted": "مقبول",
  "New Properties": "اجدد العروض",
  "For Rent": "للايجار",
  "For Sale": "للبيع",
  "Submit": "تم",
  "Rent": "ايجار",
  "Share": "مشاركة",
  "Filters": "تصنيف",
  "Setting": "الاعدادات",
  "Search Results": "نتائج التصنيف",
  "Properties Found": "عروض متاحة",
  "Submitted": "المختارة",
  "View all": "عرض الكل",
  "Search": "البحث",
  "Any": "اى",
  "Home": "الصفحة الرئيسية",
  "HOME": "الرئيسية",
  "Brands": "الماركة",
  "Name": "الاسم",
  "Colors": "اللون",
  "Tourism Services\nHotel Reservation": "خدمات سياحية\nحجز فنادق",
  "Apartments for Rent & Sell\nDaily Finished Apartments": "شقق للبيع والايجار\nشقق يومية مفروشة",
  "Daily Finished Apartments\nApartments Rent & Sell":
  "شقق مفروشة يومية\rشقق للبيع والايجار",
  "Hotel Reservation\nTourism Services": "حجز فنادق\rخدمات سياحية",
  "Models": "الموديل",
  "Old Password": "كلمة المرور الحالية",
  "Change Password": "تغيير كلمة المرور",
  "Choose date": "اختار تاريخ",
  "Without Driver": "بدون سائق",
  "With Driver": "بسائق",
  "Find a Thousand Offers": "العديد من العروض متاحة",
  "For Sell & Rent & Share": "للبيع او الايجار او المشاركة",
  "Profile": "الملف الشخصي",
  "PROFILE": "الملف الشخصي",
  "Profile details": "تفاصيل الملف الشخصي",
  "LogOut": "تسجيل خروج",
  "Logout": "تسجيل الخروج",
  "City: ": "المدينة: ",
  "Region: ": "المنطقة: ",
  "Address: ": "العنوان: ",
  "ar": "عربي",
  "Full Name": "الاسم بالكامل",
  "SignUp": "تسجيل جديد",
  "status": "الحالة",
  "Reviews": "تقييم",
  "Amenities": "ملحقات",
  "FAV": "المفضلة",
  "Apply Filters": "صنف",
  "Select Amenities": "حدد الملحقات",
  "Category": "قسم",
  "Sub Category": "قسم فرعي",
  "Price": "السعر",
  "Deposit": "المقدم",
  "Insurance": "التأمين",
  "Handovered": "تسليم",
  "cancel": "الغاء",
  "favourite": "المفضلة",
  "FAVOURITE": "المفضلة",
  "Favourite": "المفضلة",
  "For Share": "للمشاركة",
  "SUBMIT": "تم",
  "Yes": "نعم",
  "From": "من",
  "To": "الى",
  "Apartments for Rent & Sell": "شقق للبيع والايجار",
  "Tourism Services": "خدمات سياحية",
  "No": "لا",
  "New User": "مستخدم جديد",
  "Cancel": "الغاء",
  "Accept": "قبول",
  "User Name": "اسم المستخدم",
  "User Name: ": "اسم المستخدم: ",
  "First Name: ": "الاسم الاول: ",
  "Last Name: ": "الاسم الاخير: ",
  "Email: ": "لبريد الالكتروني: ",
  "Phone: ": "رقم الهاتف: ",
  "Country: ": "الدولة: ",
  "region: ": "المنطقة: ",
  "Birth Date: ": "تاريخ الميلاد: ",
  "update": "تحديث",
  "old Password: ": "كلمة المرور القديمة: ",
  "new Password: ": "كلمة المرور الجديدة: ",
  "save": "حفظ",
  "Subject: ": "عنوان: ",
  "phone: ": "رقم الهاتف: ",
  "email: ": "البريد الالكتروني: ",
  "Birthday: ": "تاريخ الميلاد: ",
  "Save": "حفظ",
  "delete": "حذف",
  "submit": "عدل",
  "Password: ": "كلمة المرور: ",
  "new email: ": "البريد الالكتروني الجديد: ",
  "Update About": "تحديث النبذة",
  "send": "ارسل",
  "Status": "الحالة",
  "Your birthday": "تاريخ الميلاد",
  "Double Click to exit app": "اضغط مرتين للخروج من التطبيق",
  "enter email": "ادخل البريد الالكتروني",
  "password do not match": "كلمة المرور لا تتطابق",
  "confirm Password": "تاكيد كلمة المرور",
  "New Password": "كلمة المرور",
  "NEW PASSWORD": "كلمة المرور",
  "Info": "معلومات",
  "Policy and Privacy": "سياسة الخصوصية",
  "Contact Us": "تواصل معنا",
  "CONTACT US": "تواصل معنا",
  "About Us": "عنا",
  "Terms Conditions": "الشروط و الاحكام",
  "Failed to load": "خطاء في التحميل",
  "Description": "وصف",
  "Media": "وسائط",
  "Reserve": "حجز",
  "renting cars": "ايجار سيارات",
  "airport reception": "استقبال مطار",
  "Land sale and rent": "بيع وايجار اراضي",
  "Facilities for rent & sell": "بيع وايجار منشأت",
  "Apartment rental": "ايجار شقق مفروشة",
  "Apartments for sell": "بيع و ايجار شقق",
  "Apartments for rent": "ايجار شقق مفروشة",
  "Establishments":"المؤسسات",
  "lands":"الأراضي"
};
