const Map<String, String> en = {
  "UserName": "UserName",
  "Login": "Login",
  "LOGIN": "LOGIN",
  "SIGN UP": "SIGN UP",
  "register": "register",
  "Reset Password": "Reset Password",
  "OR": "OR",
  "incorrect email or password": "incorrect email or password",
  "Password": "Password",
  "Username": "Username",
  "Forgot your password?": "Forgot your password?",
  "Don't Have an Account? Sign up": "Don't Have an Account? Sign up",
  "Please Accept Our Terms To Can Make A New Account!":
  "Please Accept Our Terms To Can Make A New Account!",
  "REGISTER": "REGISTER",
  "Terms & Conditions": "Terms & Conditions",
  "First Name": "First Name",
  "Tap back again to leave": "Tap back again to leave",
  "Last Name": "Last Name",
  "Email": "Email",
  "Agree": "Agree",
  "Confirm Password": "Confirm Password",
  "you are sign in": "you are sign in",
  "UserName Is Already Exist": "UserName Is Already Exist",
  "Email Is Already Exist": "Email Is Already Exist",
  "Is Required": "Is Required",
  "Should Be At Least 6 Characters": "Should Be At Least 6 Characters",
  "Password and Confirm Password Doesn't Match":
  "Password and Confirm Password Doesn't Match",
  "Should Be At Least 4 Characters": "Should Be At Least 4 Characters",
  "Invalid Email": "Invalid Email",
  "Next": "Next",
  "Send": "Send",
  "Restore Account": "Restore Account",
  "Delete Account": "Delete Account",
  "Already Have an Account? Sign in": "Already Have an Account? Sign in",
  "Email Verified": "Email Verified",
  "the code doesn't match check your code or change Email":
  "the code doesn't match check your code or change Email",
  "EMAIL VERIFICATION": "EMAIL VERIFICATION",
  "verification code": "verification code",
  "Verify": "Verify",
  "Failed to load Countries": "Failed to load Countries",
  "Failed to load Regions": "Failed to load Regions",
  "Failed to load Cities": "Failed to load Cities",
  "ADDRESS": "ADDRESS",
  "Select Country": "Select Country",
  "Select City": "Select City",
  "Select Region": "Select Region",
  "Add Your Address Here": "Add Your Address Here",
  "Orders": "Orders",
  "Explore Orders": "Explore Orders",
  "Details": "Details",
  "Status: ": "Status: ",
  "refused": "refused",
  "accepted": "accepted",
  "no seen yet": "no seen yet",
  "Order Updates": "Order Updates",
  "Add Your description Here": "Add Your description Here",
  "Submit": "Submit",
  "Offers": "Offers",
  "Assignment": "Assignment",
  "Active": "Active",
  "Home": "Home",
  "HOME": "HOME",
  "Search": "Search",
  "New Properties": "New Properties",
  "View all": "View all",
  "favourite": "favourite",
  "FAVOURITE": "FAVOURITE",
  "Favourite": "Favourite",
  "Apply Filters": "Apply Filters",
  "Price": "Price",
  "Deposit": "Deposit",
  "Insurance": "Insurance",
  "Reviews": "Reviews",
  "Category": "Category",
  "Amenities": "Amenities",
  "FAV": "FAV",
  "Select Amenities": "Select Amenities",
  "Sub Category": "Sub Category",
  "For Rent": "For Rent",
  "For Sale": "For Sale",
  "For Share": "For Share",
  "Find a Thousand Offers": "Find a Thousand Offers",
  "Profile": "Profile",
  "PROFILE": "PROFILE",
  "Sell": "Sell",
  "Share": "Share",
  "For Sell & Rent & Share": "For Sell & Rent & Share",
  "Profile details": "Profile details",
  "My Offers": "My Offers",
  "Notifications": "Notifications",
  "LogOut": "LogOut",
  "Logout": "Logout",
  "SignUp": "SignUp",
  "Brands": "Brands",
  "Models": "Models",
  "Colors": "Colors",
  "Change Password": "Change Password",
  "Any": "Any",
  "Name": "Name",
  "Choose date": "Choose date",
  "Without Driver": "Without Driver",
  "With Driver": "With Driver",
  "Full Name": "Full Name",
  "Pending": "Pending",
  "Archived": "Archived",
  "Update": "Update",
  "Setting": "Setting",
  "Submitted": "Submitted",
  "Search Results": "Search Results",
  "Properties Found": "Properties Found",
  "Title: ": "Title: ",
  "Order No.: ": "Order No.: ",
  "Paper Size": "Paper Size",
  "Paper Type": "Paper Type",
  "Paper Color": "Paper Color",
  "Printing Layout": "Printing Layout",
  "Printing Side": "Printing Side",
  "Paper Binding": "Paper Binding",
  "Number Of Copies: ": "Number Of Copies: ",
  "Linguistic Correction": "Linguistic Correction",
  "Delivery": "Delivery",
  "Location": "Location",
  "Downloading File: ": "Downloading File: ",
  "Make Offer": "Make Offer",
  "Cost": "Cost",
  "Delivery Cost": "Delivery Cost",
  "After fee": "After fee",
  "Days": "Days",
  "Disable": "Disable",
  "City: ": "City: ",
  "Region: ": "Region: ",
  "Address: ": "Address: ",
  "Days: ": "Days: ",
  "Hours: ": "Hours: ",
  "Minutes: ": "Minutes: ",
  "Cameras": "Cameras",
  "Accessories": "Accessories",
  "Assignments": "Assignments",
  "Arrival": "Arrival",
  "cancel": "cancel",
  "Rent": "Rent",
  "Your Montage Orders": "Your Montage Orders",
  "Your Photography Orders": "Your Photography Orders",
  "Translation": "Translation",
  "Your Translation Orders": "Your Translation Orders",
  "Montage": "Montage",
  "Order Details": "Order Details",
  "Url Link": "Url Link",
  "To: ": "To: ",
  "From: ": "From: ",
  "SUBMIT": "SUBMIT",
  "Yes": "Yes",
  "No": "No",
  "Cancel": "Cancel",
  "Accept": "Accept",
  "From": "From",
  "To": "To",
  "Apartments for Rent & Sell": "Apartments for Rent & Sell",
  "Tourism Services": "Tourism Services",
  "New User": "New User",
  "Picture Size": "Picture Size",
  "Upload video": "Upload video",
  "Add Your Description Here": "Add Your Description Here",
  "not seen yet": "not seen yet",
  "Refused": "Refused",
  "Accept ": "Accept",
  "Edit ": "Edit",
  "User Name": "User Name",
  "User Name: ": "User Name: ",
  "First Name: ": "First Name: ",
  "Last Name: ": "Last Name: ",
  "Email: ": "Email: ",
  "Mobile": "Mobile",
  "Country: ": "Country: ",
  "region: ": "region: ",
  "Birth Date: ": "Birth Date: ",
  "update": "update",
  "Tourism Services\nHotel Reservation": "Tourism Services\nHotel Reservation",
  "Apartments for Rent & Sell\nDaily Finished Apartments": "Apartments for Rent & Sell\nDaily Finished Apartments",
  "Daily Finished Apartments\nApartments Rent & Sell":
  "Daily Finished Apartments\nApartments Rent & Sell",
  "Hotel Reservation\nTourism Services": "Hotel Reservation\nTourism Services",
  "Old Password": "Old Password",
  "Default address": "Default address",
  "New address": "New address",
  "old Password: ": "old Password: ",
  "new Password: ": "new Password: ",
  "email: ": "email: ",
  "Birthday: ": "Birthday: ",
  "No sample yet": "No sample yet",
  "Sample": "Sample",
  "Just now": "Just now",
  "yesterday": "yesterday",
  "password do not match": "password do not match",
  "confirm Password": "confirm Password",
  "New Password": "New Password",
  "Policy and Privacy": "Policy and Privacy",
  "Contact Us": "Contact Us",
  "CONTACT US": "CONTACT US",
  "About Us": "About Us",
  "Terms Conditions": "Terms & Conditions",
  "Failed to load": "Failed to load",
  "Description": "Description",
  "Media": "Media",
  "Reserve": "Reserve",
  "renting cars": "renting cars",
  "airport reception": "airport reception",
  "Land sale and rent": "Land sale and rent",
  "Facilities for rent & sell": "Facilities for rent & sell",
  "Apartments for sale": "Apartments for sale",
  "Apartment for rent": "Apartment for rent",
  "Establishments": "Establishments",
  "lands" : "lands",
};
